---
- when: _icat is mapping
  block:
    - name: validate database config params
      when: _validate
      assert:
        that:
          - _icat.catalog_database_type in ('mysql', 'oracle', 'postgres')
          - _icat.db_port | int >= 1 and _icat.db_port | int <= 65535

    - include_tasks: _cfg_template.yml
      vars:
        _cfg_template_dest_file: etc/irods/database_config.json

- meta: flush_handlers
