---
- include_tasks: _cfg_template.yml
  vars:
    _cfg_template_dest_file: etc/irods/host_access_control_config.json

- name: host_access_control_config | ensure known that changes were made
  meta: flush_handlers
