---
- import_tasks: odbc.yml

- import_tasks: host_access_control_config.yml

- import_tasks: hosts_config.yml

- include_tasks: irods_environment.yml
  vars:
    _for_server: true

- import_tasks: server_config.yml

- import_tasks: service_account.yml
